ImagicalMine/ImagicalMine

src/pocketmine/network/protocol/LoginPacket.php
src/pocketmine/network/protocol/LoginPacket__32bit.php
src/pocketmine/network/protocol/LoginPacket__64bit.php

Here's the fix compliments of Intyre =) - tested, works like a champ!

Added getByte before ->slim in LoginPacket to fix player skins

---

src/pocketmine/Player.php
src/pocketmine/Player__32bit.php
src/pocketmine/Player__64bit.php

hasPermission() on null fix.

---

src/pocketmine/PocketMine.php

http://minecraft.gamepedia.com/Pocket_Edition_version_history

Set to 0.13.0

---

src/pocketmine/Player.php
src/pocketmine/inventory/PlayerInventory.php

(Re)fixed the issue where items could not be added to hotbar in creative mode. This was fixed before but overwritten
I take it these changes were reverted by accident and everybody is happy if they are merged back in?

(Re)fixed the issue where items could not be added to hotbar in creative mode

---

src/pocketmine/item/AcaciaDoor.php
src/pocketmine/item/BirchDoor.php
src/pocketmine/item/DarkOakDoor.php
src/pocketmine/item/Item.php
src/pocketmine/item/JungleDoor.php
src/pocketmine/item/SpruceDoor.php

You can Merge this in. There are some items that are not placeable but at least they are on the creative inventory to test with. Doors were the main one I wanted working before submitting and they are now.
This will fail Travis due to that the partially changed CraftingManager.php that got included when I branched - I can confirm I have tested and works fine

0.13 creative items

---

src/pocketmine/tile/Furnace.php

fix furnace crash

---

src/pocketmine/inventory/CraftingManager.php

fix crafting table can't craft plank

Fix Plank craft bug

---

src/pocketmine/block/SnowLayer.php

Mentioned in the main issues thread

Fixes SnowLayer bug

---

src/pocketmine/block/SnowLayer.php

Reverts ImagicalCorp/ImagicalMine#248 Forgot a crucial part of the code

Revert "Fixes SnowLayer bug"

---

src/pocketmine/block/SnowLayer.php

I actually fixed it this time.

Fixed the SnowLayer Bug

---

src/pocketmine/block/Trapdoor.php

- Fixed RakLib error
- Re-added sound when the trapdoor is opening (no Redstone)
- Fix some space in fuction "onRedstoneUpdate"

Fixed some problem  with trapdoor

---

src/pocketmine/block/IronTrapdoor.php

Improve IronTrapdoor

---

src/pocketmine/PocketMine.php

I only updated the version in the PocketMine source file. Team members - do more edits by pushing to the 0.13.1-update branch.

0.13.1 updates/support

---

src/pocketmine/entity/CavernSpider.php
src/pocketmine/entity/Chicken.php
src/pocketmine/entity/Cow.php
src/pocketmine/entity/Sheep.php

i want Travis to test, i didn't want to commit myself without asking.

Improved code style and added some drops for some entities

---

src/pocketmine/command/defaults/VanillaCommand.php

FIX: added check of input in VannillaCommand - tracked down on crashes …
caused by tp commands ecoron#2

patch-vanillacommand-1 - added check of input in VannillaCommand

---

src/pocketmine/Player.php

by @onebone in the pocketmine pull request. If he doesn't like, revert this.

Fix for #402

---

src/pocketmine/item/Item.php

Reverts ImagicalCorp/ImagicalMine#428

Revert "Fix one bug of #427"

---

src/pocketmine/entity/Human.php

Fix Skin Bug On Join
My server test 
play.applecraft.cf
19132 and 19133

Fix Skin Bug On Join

---

start.cmd
start.sh

i am serious how can they read it in 1 second lol.

should we give them time to read?

---

src/pocketmine/item/Item.php

Why 2 $this->hasCompoundTag @ZombiePower??

---

src/pocketmine/entity/Wolf.php

Updated Wolf.php to use AddEntityPacket to fix a crash.

Fixed a crash when spawning a wolf

---

src/pocketmine/block/Glass.php
src/pocketmine/block/Lapis.php
src/pocketmine/block/Stone.php
src/pocketmine/item/BakedPotato.php
src/pocketmine/item/Brick.php
src/pocketmine/item/Coal.php
src/pocketmine/item/CookedChicken.php
src/pocketmine/item/CookedFish.php
src/pocketmine/item/CookedPorkchop.php
src/pocketmine/item/CookedRabbit.php
src/pocketmine/item/Diamond.php
src/pocketmine/item/Emerald.php
src/pocketmine/item/GoldIngot.php
src/pocketmine/item/IronIngot.php
src/pocketmine/item/ItemBlock.php
src/pocketmine/item/NetherBrick.php
src/pocketmine/item/NetherQuartz.php
src/pocketmine/item/Redstone.php
src/pocketmine/item/Steak.php

Implement items getSmeltingExp()

smelting exp

---

src/pocketmine/inventory/CraftingManager.php

So i updated all recipes, added new recipes & sorted out from Shapeless over Shaped to BigShaped.

Updated all recipes & Sorted

---

src/pocketmine/inventory/CraftingManager.php

Don't bother commenting on this :)

Update to PHP 7 branxh

---

README.md
src/pocketmine/block/NetherPortal.php
src/pocketmine/inventory/CraftingManager.php

Updates from master to php7 branch

PHP 7 branch update

---

src/pocketmine/inventory/CraftingManager.php

Added wooden buttons

---

src/pocketmine/inventory/CraftingManager.php

WOODEN_PRESSURE_PLATE cannot be created with WOOD. Also needed other WOODEN_PLANK types adding

WOODEN_PRESSURE_PLATE: Remove WOOD, Add WOODEN_PLANK

---

src/pocketmine/inventory/CraftingManager.php

Keep branch updated :)

---

src/pocketmine/entity/ThrownExpBottle.php

This caused another JENKINS-STUCK

LOL ; is missing

---

src/pocketmine/block/Noteblock.php

now the downSideId ($this->getSide(0)->getId())  is persisted on place and onUpdate.
seems the call (Line 64) was causing the loop.
btw. the code in onActivate is a little bit reordered.

maybe possible fix for #604

---

src/pocketmine/Player.php
src/pocketmine/entity/AttributeManager.php

Hunger is not persisted across sessions. Should fix #716

Make Hunger Save and Load

---

src/pocketmine/entity/Minecart.php

just adding the getName() and a todo block for properties. maybe someone can add the right values.

possible fix for #732

---

src/pocketmine/entity/Minecart.php

from wikipage, should be the right one

Update Minecart.php add networkid

---

src/pocketmine/block/Pumpkin.php

Just a small fix about building Iron Golems ...

fixed building iron golem

---

src/pocketmine/block/Dispenser.php
src/pocketmine/inventory/DispenserInventory.php
src/pocketmine/inventory/InventoryType.php
src/pocketmine/tile/Dispenser.php
src/pocketmine/tile/Tile.php

Now you can merge this xD, I've no experience with GitHub and I don't know if it work, test before merge please

Dispenser GUI

---

src/pocketmine/PocketMine.php
src/pocketmine/block/CocoaPod.php
src/pocketmine/block/Leaves2.php
src/pocketmine/block/Rail.php
src/pocketmine/block/WoodenButton.php
src/pocketmine/entity/Minecart.php
src/pocketmine/event/entity/EntityEnterPortalEvent.php
src/pocketmine/inventory/CraftingManager.php
src/pocketmine/item/Bucket.php
src/pocketmine/katana/Katana.php

If I did something evil with this, please let me know

Fix Timezone in 0.14 branch (and 9 more commits)

---

src/pocketmine/entity/Minecart.php
src/pocketmine/item/Minecart.php

now its possible to place a minecart.
but it's still not moving yet and needs also some more improvements (like the boat).
changes are taken from Genisys project and this works
i tested it on my dev server, seems to be working for now

minecart-patch-3, its now placeable

---

src/pocketmine/entity/Entity.php
src/pocketmine/item/Item.php

Reverts ImagicalMine/ImagicalMine#802

Revert "onPlayerAction-patch-1 - add generic method to Item/Entity"

---

src/pocketmine/block/LitPumpkin.php
src/pocketmine/block/Pumpkin.php

I'll make it short: building an Iron Golem didn't work for all perspectives. With this commit it's working.
Changed also the stuff for LitPumpkin - building snow and iron golems is now also possible with a pumpkin lit.

Iron Golem is now working from all perspectives

---

src/pocketmine/block/DoubleSlab.php
src/pocketmine/block/Slab.php

Ermmmm first time use Github ...
http://minecraft.gamepedia.com/Slab

incorrect meta of slab and double slab

---

src/pocketmine/Player.php
src/pocketmine/block/Rail.php
src/pocketmine/block/RailBlock.php
src/pocketmine/entity/Entity.php
src/pocketmine/entity/Minecart.php
src/pocketmine/item/Item.php

this changes makes Minecart movable.
- it is breakable
- player can start moving
- player can stop moving by jumping
- updated rail check, so it detects different types of connected rails
- tested on my dev
maybe later on some improvements of the player position in cart can be done, and changing speed on different railtypes would be also nice...

Minecart can moving now

---

README.md

That wasn't supposed to happen.. (Did it?)
an web address looks like this http://blahblah:xxxx.bla

Fixed corrupt link

---

src/pocketmine/lang/locale/deu.ini

German translation for fill

---

src/pocketmine/level/generator/object/AcaciaTree.php
src/pocketmine/level/generator/object/DarkOakTree.php
src/pocketmine/level/generator/object/Tree.php

Grow correct tree from saplings

---

.travis.yml
src/pocketmine/Player.php
src/pocketmine/PocketMine.php
src/pocketmine/Server.php
src/pocketmine/block/DarkOakWoodStairs.php
src/pocketmine/block/DetectorRail.php
src/pocketmine/block/DoubleSlab.php
src/pocketmine/block/JungleWoodStairs.php
src/pocketmine/block/LitPumpkin.php
src/pocketmine/block/NetherPortal.php
src/pocketmine/block/Pumpkin.php
src/pocketmine/block/WoodenButton.php
src/pocketmine/entity/Entity.php
src/pocketmine/entity/ThrownExpBottle.php
src/pocketmine/inventory/CraftingManager.php
src/pocketmine/item/Bucket.php
src/pocketmine/item/Item.php
src/pocketmine/item/Minecart.php
src/pocketmine/level/Level.php
src/pocketmine/network/protocol/Info.php
src/pocketmine/resources/pocketmine.yml
start.sh

i think now the changes from master are in php7 branch - #847.
i didn't merged it finaly yet, so you can take a look on the changes and check
if i something have forgotten or changed it in the wrong way, because there was a lot of conflicts.
If anything is fine it can merged into the origin branch php7.

merge master into php7

---

src/pocketmine/level/generator/biome/Biome.php
src/pocketmine/level/generator/normal/biome/PlainBiome.php
src/pocketmine/level/generator/normal/biome/SwampBiome.php
src/pocketmine/level/generator/populator/Flower.php
src/pocketmine/level/generator/populator/Flowers.php

OK guys, first attempt at adding something completely new  This is designed to generate flowers when the world is built.  Comments appreciated on the approach.
Basically flowers should not generate in all biomes based on data from http://minecraft.gamepedia.com/Flower (Sunflower Plain and Flower Forest excluded).
If you think I should add the defaults in a different way than in Biome,php then let me know.  Have modelled the process on TallGrass.
Next steps following this is to add some way to determine the block a flower can be spawned on so Dead Bushes, Cacti and Sugar Cane can be added for the desert biome.
fix #837

Generate flowers

---

src/pocketmine/PocketMine.php

Should this change, servers are not working....

? "0.13.x" ?

---

src/pocketmine/PocketMine.php

Reverts ImagicalMine/ImagicalMine#882
UNSURE PLEASE COMMENT YOUR OPINION.

Revert "? "0.13.x" ?"

---

src/pocketmine/block/Noteblock.php
src/pocketmine/level/sound/NoteblockSound.php

Fix Instrument type
Add all instrument type case (getSide(0))
Renamed istruments (in NoteBlockSound)
and Etc...

More Perfect NoteBlock

---

src/pocketmine/item/Item.php
src/pocketmine/item/ItemContainer.php

this is the first iteartion for code cleanup.
changes:
- Item extends new class ItemContainer
- ItemContainer holds all the ItemID and item related settings
- Item methods are reordered  (alphabetic)
- removed tabs and ascii header
so far i see after my testings, nothing should be breaked.
But would be nice if some other devs takes a look on it and can give some feedback.

code cleanup, reorder methods in Item , move ID settings to new class ItemContainer

---

src/pocketmine/command/SimpleCommandMap.php
src/pocketmine/command/defaults/WorldTeleportCommand.php
src/pocketmine/lang/locale/deu.ini
src/pocketmine/lang/locale/eng.ini
src/pocketmine/permission/DefaultPermissions.php

**DO NOT DELETE - LEAVE THIS IN YOUR PR**
Welcome to the ImagicalMine pull request system!
Before you make an issue, make sure your pull request matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.
If your PR matches this criteria, hooray! Submit this PR with no worries. If your PR doesn't match this criteria, please consider editing your PR to match it. Thanks for contributing to ImagicalMine!
--START PR DETAILS BELOW--
this adds a simple command, to enable players to teleport between worlds on a server.
Usage:
```
/wtp ls
#or
/wtp list
#or
/wtp <number world>
```
Permission:
```
#default op
pocketmine.command.wtp
```

add wtp command (world teleport)

---

src/pocketmine/inventory/InventoryType.php

**DO NOT DELETE - LEAVE THIS IN YOUR PR**<br>
Welcome to the ImagicalMine pull request system!<br>
Before you make an issue, make sure your pull request matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.
If your PR matches this criteria, hooray! Submit this PR with no worries. If your PR doesn't match this criteria, please consider editing your PR to match it. Thanks for contributing to ImagicalMine!<br>
**START PR DETAILS BELOW**<br>
--------------------------

Fixed inventories

---

src/pocketmine/utils/BinaryStream.php

**DO NOT DELETE - LEAVE THIS IN YOUR PR**<br>
Welcome to the ImagicalMine pull request system!<br>
Before you make an issue, make sure your pull request matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.
If your PR matches this criteria, hooray! Submit this PR with no worries. If your PR doesn't match this criteria, please consider editing your PR to match it. Thanks for contributing to ImagicalMine!<br>
**START PR DETAILS BELOW**<br>
--------------------------
This commit fix enchantments deleting inventory in MCPE 0.14.0

Fix Enchantments

---

README.md

**DO NOT DELETE - LEAVE THIS IN YOUR PR**<br>
Welcome to the ImagicalMine pull request system!<br>
Before you make an issue, make sure your pull request matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.
If your PR matches this criteria, hooray! Submit this PR with no worries. If your PR doesn't match this criteria, please consider editing your PR to match it. Thanks for contributing to ImagicalMine!<br>
**START PR DETAILS BELOW**<br>
--------------------------
I may be being picky. But I am just correcting the errors. Even though it is a small correction it should be merged, (even though some people may not notice the error!)

You should not use contractions in formal writing.

---

src/pocketmine/Player.php

Fix invalid return type.

---

src/pocketmine/tile/Dispenser.php
src/pocketmine/tile/Hopper.php

Fix invalid class name

---

src/pocketmine/item/PoisonousPotato.php
src/pocketmine/item/Spidereye.php

Error when eating:
```
Warning: Illegal offset type in C:\Users\Leonardo\Desktop\ImagicalMine-master\src\pocketmine\item\Spidereye.php on line 39
```
Now is working http://prnt.sc/ac6f1l!!
(It is my first time with PocketMine/ImagicalMine, and my first time with php after +1 year without using it.)
Sorry for my english.

Fix 'Illegal array key type' on foods that contains effects.

---

src/pocketmine/inventory/CraftingManager.php

Add recipes for flowers to your respective dyes, according with singleplayer/wiki.
Sorry for my english.

Add recipes for flowers -> dye.

---

src/pocketmine/block/Dispenser.php
src/pocketmine/block/Dropper.php
src/pocketmine/block/Hopper.php
src/pocketmine/inventory/CraftingManager.php
src/pocketmine/item/Bucket.php
src/pocketmine/item/Hopper.php
src/pocketmine/item/ItemContainer.php
src/pocketmine/tile/Dispenser.php

Added as PR for review
Have added some basic dispenser functionality (dispenses items, water and lava).  Probably needs further work.  Is in use on my server and seems to work OK, but could do with some more eyes.
Also fixed - 
* Bucket Stack Size (Should be 16 empty, but only 1 filled)
* Added recipes for Dispenser, Hopper and Dropper
* Made Hopper show correctly in inventories (has different Item ID compared to Block ID)
* Missing Level and Stone Button recipes (When did crafting manager get updated as I know I added them at some point!  Please watch what you copy and paste in people!)

Add basic Dispenser functionality

---

src/pocketmine/resources/pocketmine.yml

People could not join the server because when they attempted to, the client crashed. This allows people with under 512MB of RAM to join servers!

Fix #231371 and #231364

---

README.md

Haha! 'Clicking the here' made me laugh.

Remove unneeded 'the'

---

README.md

FakaHeda supports ImagicalMine with PHP7

Added fakaheda hosting

---

src/pocketmine/Player.php

Fix break statement on win10 fix

Fix break statement on win10 fix

---

src/pocketmine/block/Block.php
src/pocketmine/block/PoweredRepeater.php

This fixes redstone repeater errors on the console.

Repeaters fix

---

src/pocketmine/command/defaults/MakePluginCommand.php

Now this one should work :). Fixes makeplugin command so DevTools is working fine.

Fixes DevTools

---

README.md

I've added Nitrado on the hosters list. 
For questions about Nitrado.net please feel free to contact me.

Added Nitrado.net as Hoster

---

src/pocketmine/command/defaults/WorldTeleportCommand.php

- [C ] This PR actually submits something - don't use this system as a messaging service!
- [ C] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [ C] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [ C] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [ C] This PR matches the contributing guidelines - the link is just above the title field.
- [ C] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [ C] This PR has comments written in clear English - please don't write unreadable comments just for …

Code cleanup..
